export const ActionTypes = {
    SET_CARS : "SET_CARS",
    SELECTED_CARS:"SELECTED_CARS",
    REMOVE_CARS:"REMOVE_CARS",
    LOG_USER: "LOG_USER",
    SIGNIN_USER: "SIGNIN_USER",
    GET_COMMENTS: "GET_COMMENTS"
}